version: 1.0.0
name: architecto
description: "Architecto is a mobile app designed to manage labor attendance, track site stock, and maintain essential details for construction projects."

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  adaptive_theme: ^3.6.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  provider: ^6.1.2
  animate_do: ^3.3.4
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

  fonts:
    - family: "Mukta"
      fonts:
        - asset: fonts/mukta/Mukta-Regular.ttf
        - asset: fonts/mukta/Mukta-ExtraLight.ttf
          weight: 200
        - asset: fonts/mukta/Mukta-Light.ttf
          weight: 300
        - asset: fonts/mukta/Mukta-Medium.ttf
          weight: 500
        - asset: fonts/mukta/Mukta-SemiBold.ttf
          weight: 600
        - asset: fonts/mukta/Mukta-Bold.ttf
          weight: 700
        - asset: fonts/mukta/Mukta-ExtraBold.ttf
          weight: 800